### ISSUE TITLE
img.shield.io丢包非常严重

### ISSUE THREAD

**Issue by Beritra** [baomidou/baomidou.github.io#1]
宽带是北京联通。及其影响查看文档的体验，多次导致网站直接卡死。
![深度截图_选择区域_20200326010113](https://user-images.githubusercontent.com/33180702/77564285-6ba55500-6efd-11ea-9d35-9e67416cb707.png)

**Comment by qmdx** [comment]
国内地址
https://mp.baomidou.com/

国外地址
http://mybatis.plus/
